Google Colab link
Qulacs-Osaka/python-project-template pull request #21
Opened 2021-11-02 05:13 UTC by ikanago

close #18 
Jupyter Notebook から生成したページに Google Colab へのリンクが自動生成されるように設定しました．
飛ぶと main ブランチにある Notebook を Colab で開けます．
ただ，ロケットの部分にマウスをホバーさせないといけないのが分かりにくいので，今後より分かりやすい表示をしてくれる Sphinx のテーマに変更してもいいと思います．

![image](https://user-images.githubusercontent.com/28985004/139789675-ef3f5342-43c3-469f-b5c8-837785c79cb6.png)

これを有効化するにあたって，Sphinx の Notebook 用のプラグインを nbsphinx から myst_nb に変更しました．
#18 に書いた通り，nbsphinx ではうまくいかないのですが，myst_nb だとうまく生成できたのでこちらを採用しました．

2021-11-02 08:31 UTC, Hiroya-W requested changes
PRありがとうございます！
ノートブックからページの生成、Google colabへのリンクの生成とも良い感じに生成出来ていました！
1箇所、細かい修正ですがお願いします！

2021-11-02 09:00 UTC, Hiroya-W commented
確かに、https://github.com/Qulacs-Osaka/python-project-template/issues/18#issue-1035898378 にあるような、バッジだとGoogle colabへのリンクがひと目で分かりますね。
今回の場合でも、ホバーすればアイコン表示があるので分かりますし、常にページ上部にボタンが配置されてGoogle colabに飛びやすいというメリットもあるので、これもいいと思います。方法を確立していただき、ありがとうございます！

ちなみに、バッジではなく、Shpinxで生成されるページ内のボタンとしてGoogle colabへのリンクにしたのは、バッジのリンクを自動的に生成して埋め込むのが難しい、といった感じなのでしょうか？

2021-11-09 04:11 UTC, ikanago commented
> ちなみに、バッジではなく、Shpinxで生成されるページ内のボタンとしてGoogle colabへのリンクにしたのは、バッジのリンクを自動的に生成して埋め込むのが難しい、といった感じなのでしょうか？

いま使っている Sphinx のテーマを継承して新しいテーマを作ることができるようで，そうすれば好きなデザインでリンクを埋め込むことができます．ただ今回はとりあえずリンクを生成することを優先して，設定の変更だけでできる方法をとりました．

2021-11-09 05:34 UTC, Hiroya-W approved these changes
修正ありがとうございます！LGTMです！

2021-11-09 05:50 UTC, merged