Depricate pysen
Qulacs-Osaka/python-project-template pull request #26
Opened 2021-11-30 04:58 UTC by ikanago

close #25 
pysen の仕様をやめてツール群を直接インストールしました．

2021-11-30 08:24 UTC, Hiroya-W requested changes
PRありがとうございます！pysenから個別のlinterの実行への移行は、とても助かります。他のプロジェクトもこれに合わせていこうと思っています。

いくつかコメントを書きました。確認お願いします。

2021-11-30 08:24 UTC, Hiroya-W commented on Makefile
> +	$(TYPE_CHECKER) $(PROJECT_DIR)
`mypy`の型検査を分離させることには賛成です。
開発で、手元で`lint`を実行する前には、`format`も一緒に実行してくれるとタイプ数が少なく、楽だと思っています。そのような1コマンドで実行してくれる`check`ターゲットは作ってもいいと思います。
基本的に、使えるのであれば`mypy`はプロジェクトに導入してほしいので、それがデフォルトの動作としてもいいと思います。

例えば、

```Makefile
format:
lint:
type:
check: format lint type
```

のようにして、`git commit`前には`make check`を実行してもらうようにします。また、CIでは`make lint`、`make type`を実行するようにしておきます。

`mypy`の検査をパス出来ないプロジェクトでは、
- `Makefile`の`check`ターゲットのprereqから`type`を消す
- `ci.yml`から`make type`を消す、

という使い方を考えましたが、どうでしょうか？

2021-11-30 08:33 UTC, Hiroya-W commented on Makefile
> +	$(TYPE_CHECKER) $(PROJECT_DIR)
`check`の用途がikanagoさんの考えているものと変わってしまうので、`all`ターゲット作って`DEFAULT_GOAL`として設定してもいい、とも思いました

2021-12-02 05:38 UTC, ikanago commented on Makefile
> +	$(TYPE_CHECKER) $(PROJECT_DIR)
Makefile うまくまとまらないなと思ってたんですが，提案してもらった構造が一番やりやすそうです!

2021-12-02 05:56 UTC, ikanago commented
`make check` で format, lint, type を起動するようにしました．
このとき `lint` でフォーマットのチェックをやるのは無駄なので `format_check` に分離しました．
CI ではフォーマットの修正をする必要がないので `make ci` から `format_check` を呼ぶようにしました．

2021-12-03 06:08 UTC, Hiroya-W requested changes
修正ありがとうございます、使いやすくなったと思います！
残り、1箇所だけお願いします。それでOKだと思っています。

2021-12-07 04:13 UTC, merged