23 test coverage
Qulacs-Osaka/python-project-template pull request #38
Opened 2022-07-12 04:54 UTC by ikanago

close #23 
scikit-qulacs を参考に Makefile や CI の設定も更新しました．

2022-07-12 05:15 UTC, Hiroya-W requested changes
PRありがとうございます！後で qulacs-visualizer にも取り入れてカバレッジを計測してみたいと思っています！
いくつかコメントを書きました、お願いします 🙏

2022-07-12 05:15 UTC, Hiroya-W commented on Makefile
> +COVERAGE_OPT := --cov skqulacs --cov-branch
ここの、`skqulacs` って必要そうでしょうか？テスト対象のディレクトリを指定するなら、`CHECK_DIR`を指定するのが適切そうです！

2022-07-12 05:15 UTC, Hiroya-W commented on Makefile
> +COVERAGE_OPT := --cov skqulacs --cov-branch
`cov`、`cov_ci`ターゲットのコマンドでディレクトリ指定しているならここでオプションの指定はいらなさそうですが、どちらかで統一してあればOKだと思います！

2022-07-12 05:15 UTC, Hiroya-W commented on Makefile
> +	$(PYTEST) $(COVERAGE_OPT) --cov-report html $(TEST_DIR)
python-project-templateでは`CHECK_DIR`が適切そうですね

```suggestion
	$(PYTEST) $(COVERAGE_OPT) --cov-report html $(CHECK_DIR)
```

2022-07-12 05:15 UTC, Hiroya-W commented on Makefile
> +	$(PYTEST) $(COVERAGE_OPT) --cov-report xml $(TEST_DIR)
```suggestion
	$(PYTEST) $(COVERAGE_OPT) --cov-report xml $(CHECK_DIR)
```

2022-07-12 06:42 UTC, ikanago commented on Makefile
> +COVERAGE_OPT := --cov skqulacs --cov-branch
いま試してみたんですが、確かにいらないですね．削除しておきます．

2022-07-12 07:20 UTC, Hiroya-W commented on Makefile
> +COVERAGE_OPT := --cov skqulacs --cov-branch
ここ、`--cov`オプションも一緒に消すとダメそうな感じがしていて、pytestは実行されても、カバレッジが htmlcov ディレクトリに生成されなくなりそうです

2022-07-15 04:40 UTC, ikanago commented on Makefile
> +COVERAGE_OPT := --cov skqulacs --cov-branch
`--cov $(PROJECT_DIR)` を指定して，`$(CHECK_DIR)` を `$(TEST_DIR)` に変更しました．これで scikit-qulacs と同じになるのでいけそうです

2022-07-19 05:08 UTC, Hiroya-W commented on Makefile
> +COVERAGE_OPT := --cov skqulacs --cov-branch
なるほどです！
このオプションで指定するディレクトリがよく理解出来ていませんでした...。ありがとうございます。

2022-07-19 05:20 UTC, Hiroya-W commented on Makefile
> +	$(PYTEST) $(COVERAGE_OPT) --cov-report html $(TEST_DIR)
`--cov $(PROJECT_DIR)`でカバレッジを計測するコードのディレクトリを指定することを理解しました。
何度も掘り起こして申し訳ないのですが、ここで、`$(TEST_DIR)`を指定しているのは、pytestで実行するテストコードがあるディレクトリを指定しているのだと思います。pytestは自分で`test_*.py`にある関数を自動で収集してくれるので、そもそも指定しなくても良いのかな？と思っています。
現状、python-project-templateのMakefile内では`TEST_DIR`が定義されていないので、コマンド実行時にも使われていないようですが、上手く動いていそうです。

2022-07-19 06:21 UTC, Hiroya-W approved these changes
ありがとうございます！LGTMです！

2022-07-22 04:26 UTC, merged